apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deploy
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: asia-south1-docker.pkg.dev/clear-booking-470907-q6/python-app-repo/python-app:latest
        ports:
        - containerPort: 5000
      imagePullPolicy: Always
